spring.application.name=gde_website

spring.datasource.url=jdbc:postgresql://localhost:5432/${.env.secret.POSTGRES_DB}
spring.datasource.username=${.env.secret.POSTGRES_USER}
spring.datasource.password=${.env.secret.POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
