# Checks links inside Markdown and HTML repo files

# What type of files need to be checked
extensions = ["md", "html"]

# Excluded links
exclude = [
    "https://localhost",
    "http://localhost",
    "^https://www\\.figma\\.com/",
]

# Тimeout in seconds
timeout = 10

# Maximum number of parallel requests
max_concurrency = 10
